include themes/blossom.conf

# Font configuration
font_family     JetBrainsMono Nerd Font
bold_font       auto
italic_font     auto
font_size       13

# Window layout
window_padding_width  0
background_opacity 0.95

# Tab bar styles
tab_bar_edge     bottom
tab_bar_style    fade

mouse_map ctrl+left press ungrabbed mouse_handle_click selection link
